try
{
    console.log('start of try');

    console.log('end of try');
}
catch
{
    console.log('error has occured');
}